[conf]
    service_name = "Mysql2"
    service_addr = "coms.xiaopan233.club"
    service_port = 7778
    service_database = "/mysql"
    user = "root"
    password = "123456"
    max_conn_life_time = 100
    max_open_conn = 20
    max_idle_conn = 10