# This is dev environment config

[base]
    debug_mode="debug"
    time_location="Asia/Chongqing"

[http]
    addr = ":8083"  # 设置端口操作
    read_timeout = 10 # 读取超时时长
    write_timeout = 10 # 写入超时时长
    max_header_bytes = 20 # 最大的 header
    allow_host = [
        "127.0.0.1",
        "192.168.1.1",
        "192.168.144.97"
    ]

[log]
    log_level = "trace"         #日志打印最低级别
    [log.file_writer]           #文件写入配置
        on = true
        log_path = "./logs/log_test.log"
        wf_log_path = "./logs/log_test.wf.log"
    [log.console_writer]        #工作台输出
        on = true
        color = true

